"use client";

import { animate, motion, useMotionValue, useReducedMotion, useSpring } from "motion/react";
import { useEffect, useRef } from "react";
import { cx } from "@/lib/format";

/** public/brand/peek-dog.png — generated by scripts/extract-peek-dog.ts */
const SRC = "/brand/peek-dog.png";
const RATIO = 200 / 328; // height / width
const EDGE = 0.665; // the panel edge sits 66.5% down the image
const HEADROOM = 22; // room above the head for the hop

/**
 * The golden retriever peeking over the Add-a-dog modal's top edge.
 * Two layers of the same image: the head (clipped at the edge, so it rises from *behind* the panel,
 * tilts toward the cursor, blinks on open and hops on success) and the chin + paws resting on the panel.
 */
export function PeekDog({ hop, width = 150, className }: { hop: number; width?: number; className?: string }) {
  const reduced = useReducedMotion();
  const height = width * RATIO;
  const above = height * EDGE;

  const tiltRaw = useMotionValue(0);
  const tilt = useSpring(tiltRaw, { stiffness: 140, damping: 16 });
  const y = useMotionValue(reduced ? 0 : above * 0.85);
  const squash = useMotionValue(1);
  const paws = useMotionValue(reduced ? 1 : 0);
  const ref = useRef<HTMLDivElement>(null);

  // rise from behind the edge, paws land, then a blink
  useEffect(() => {
    if (reduced) return;
    const a = animate(y, 0, { type: "spring", stiffness: 260, damping: 19, delay: 0.12 });
    const b = animate(paws, 1, { duration: 0.2, delay: 0.32 });
    const c = animate(squash, [1, 0.9, 1], { duration: 0.22, delay: 0.8 });
    return () => {
      a.stop();
      b.stop();
      c.stop();
    };
  }, [reduced, y, paws, squash]);

  // head tilt follows the cursor's x position (±6°)
  useEffect(() => {
    if (reduced) return;
    const onMove = (e: MouseEvent) => {
      const r = ref.current?.getBoundingClientRect();
      if (!r) return;
      const dx = (e.clientX - (r.left + r.width / 2)) / (window.innerWidth / 2);
      tiltRaw.set(Math.max(-6, Math.min(6, dx * 6)));
    };
    window.addEventListener("mousemove", onMove);
    return () => window.removeEventListener("mousemove", onMove);
  }, [reduced, tiltRaw]);

  // happy hop on success
  useEffect(() => {
    if (!hop || reduced) return;
    const a = animate(y, [0, -HEADROOM + 4, 0, -8, 0], { duration: 0.75, ease: "easeOut" });
    return () => a.stop();
  }, [hop, reduced, y]);

  const img = (top: number) => (
    // eslint-disable-next-line @next/next/no-img-element
    <img src={SRC} alt="" width={width} height={height} draggable={false} className="absolute left-0 max-w-none select-none" style={{ top, width, height }} />
  );

  return (
    <div
      ref={ref}
      aria-hidden
      className={cx("pointer-events-none absolute top-0 left-1/2 -translate-x-1/2", className)}
      style={{ width }}
    >
      {/* the whole dog tilts together, pivoting on the panel edge, so head and paws never split */}
      <motion.div className="absolute inset-x-0 top-0" style={{ rotate: tilt, originX: 0.5, originY: 0 }}>
      {/* head: clipped at the panel edge so it appears to rise from behind it */}
      <div className="absolute inset-x-0 bottom-0 overflow-hidden" style={{ height: above + HEADROOM }}>
        <motion.div className="absolute inset-0" style={{ y, scaleY: squash, originY: 1 }}>
          {img(HEADROOM)}
        </motion.div>
      </div>
      {/* chin + paws resting on the panel */}
      <motion.div className="absolute inset-x-0 top-0 overflow-hidden" style={{ height: height - above, opacity: paws }}>
        {img(-above)}
      </motion.div>
      </motion.div>
    </div>
  );
}
